use_frameworks!

platform :ios, '12.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'XDUIKitTools_Example' do
  pod 'XDUIKitTools', :path => '../'

  target 'XDUIKitTools_Tests' do
    inherit! :search_paths

    
  end
end
